# Generated by Django 5.1.4 on 2025-01-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del servicio o API', max_length=255)),
                ('url', models.URLField(help_text='URL del endpoint', unique=True)),
                ('last_checked', models.DateTimeField(blank=True, help_text='Última vez que se revisó', null=True)),
                ('status', models.BooleanField(default=True, help_text='Estado actual del servicio')),
            ],
        ),
    ]
